### ISSUE TITLE
tString concat 改成 alloc + write, 性能提升

### ISSUE THREAD

**Issue by yejiayu** [eleme/node-thrift-protocol#2]
今天把原本的各种自定义类型 class 改成 function 后性能并没有显著提升

想到能不能从 buffer 上找突破口

网上翻了点文章加看 buffer js 层面的源码后把
```js
// tString 修改前
if (!(str instanceof Buffer)) str += '';
let sbuf = new Buffer(str, enc);
return Buffer.concat([ new TInt32(sbuf.length), sbuf ]));

// tString 修改后
if (!(str instanceof Buffer)) str += '';

const length = Buffer.byteLength(str, enc);
const buf = Buffer.allocUnsafe(length + 4);
buf.writeInt32BE(length);
if (str instanceof Buffer) {
  str = str.toString();
}

buf.write(str, 4);
return buf;
```
性能提升了一倍左右, 处理的字符串越多越明显, 具体可以看下 benchmark

https://github.com/yejiayu/node-thrift-protocol/tree/benchmark
npm i && npm run benchmark

如果能把现在代码中的 concat 形式都改了性能应该能得到很大提升? 不过因为结构比较特殊似乎不太好改

**Comment by YanagiEiichi** [comment]
嗯，这么写确实少创建了一个字符串的 Buffer 对象。。

**Comment by yejiayu** [comment]
这个优化一波性能上不是起飞?

**Comment by YanagiEiichi** [comment]
是的，而且不仅仅是这个仓库，其它相关的也可以动一波。。

**Comment by yejiayu** [comment]
https://github.com/yejiayu/node-thrift-protocol/blob/benchmark/benchmark/shim/encode3.js

优化了一波, 提升了5倍左右

类似 concat 的 copy 操作全部移除, 统一 push 到一个数组里面一次性创建一个 buffer 然后 write 各种类型数据

**Comment by YanagiEiichi** [comment]
👍  

TMessage 的 concat 名为 toBuffer 更合适吧。。

可提 PR
